name: Deploy to Github Pages
on:
  push:
    branches:
      - main
jobs:
  gh-pages-deploy:
    name: Deploying to Github Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - name: Install packages
        working-directory: ./app
        run: yarn
      - name: Set Creds
        working-directory: ./app
        run: git config user.name "yurinogueira" && git config user.email "yurinogueira@id.uff.br"
      - name: Deploy
        working-directory: ./app
        run: yarn deploy